import = [
    "~/.config/alacritty/themes/themes/.one_dark.toml"
]

[window]
dimensions = { columns = 122, lines = 34 }
padding = { x = 5, y = 5 }

# opacity =  50.0
# blur = true

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 17.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors.primary]
background = "#363636"
