[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 125, lines = 36 }
padding = { x = 5, y = 5 }
position = { x = 75, y = 100 }
# opacity = 0.8
# blur = true
decorations = "buttonless"
# decorations = "full"
decorations_theme_variant = "dark"

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 18.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors.primary]
background = "#363636"

[general]
import = ["~/.config/alacritty/themes/themes/.one_dark.toml"]
